firsttime: true
enabled : true
pokecordclone: true
poketwo: true
autocatch: true
autorelease: true
lowercasepokemon: true
intervalcatching: false
enablewhitelist: false
whitelist: [Weedle, Kakuna]
enableblacklist: false
blacklist: [Bulbasaur, Ivysaur]
autocatchdelay: [2, 4]
minimumiv: 50
prefixes: {997934948344168934: 'p!', 452605484358712643: ';'}
channels: [452605484358712643]
interval: [69, 420]
